export const ROUTES_NAMES = {
    HOMEPAGE: "NAVBAR.HOMEPAGE",
    BIO: "NAVBAR.BIO",
    SKILLS: "NAVBAR.SKILLS",
    IT_SKILLS: "NAVBAR.IT_SKILLS",
    SOFT_SKILLS: "NAVBAR.SOFT_SKILLS",
    OTHER_SOFTWARE_SKILLS: "NAVBAR.OTHER_SOFTWARE_SKILLS",
    EXPERIENCES: "NAVBAR.EXPERIENCES",
    MAIN_EXPERIENCES: "NAVBAR.MAIN_EXPERIENCES",
    SIDE_EXPERIENCES: "NAVBAR.SIDE_EXPERIENCES",
    HOBBIES: "NAVBAR.HOBBIES",
    CONTACT_ME: "NAVBAR.CONTACTS",
    SEARCH: "NAVBAR.SEARCH",
    FILES: "NAVBAR.FILES"
}