export const CONTACT_ME_FORM = {
    FULLNAME: {
        PLACEHOLDER: "FORM_FIELD.NAME.PLACEHOLDER",
        LABEL: "FORM_FIELD.NAME.LABEL",
    },
    EMAIL: {
        PLACEHOLDER: "FORM_FIELD.EMAIL.PLACEHOLDER",
        LABEL: "FORM_FIELD.EMAIL.LABEL",
    },
    EMAIL_COPY: {
        PLACEHOLDER: "FORM_FIELD.COPY.PLACEHOLDER",
        LABEL: "FORM_FIELD.COPY.LABEL"
    },
    PHONE_PREFIX: {
        PLACEHOLDER: "FORM_FIELD.PREFIX.PLACEHOLDER",
        LABEL: "FORM_FIELD.PREFIX.LABEL",
    },
    PHONE_NUMBER: {
        PLACEHOLDER: "FORM_FIELD.PHONE.PLACEHOLDER",
        LABEL: "FORM_FIELD.PHONE.LABEL",
    },
    ATTACHMENT: {
        PLACEHOLDER: "FORM_FIELD.ATTACHMENT.PLACEHOLDER",
        LABEL: "FORM_FIELD.ATTACHMENT.LABEL",
    },
    MESSAGE: {
        PLACEHOLDER: "FORM_FIELD.MESSAGE.PLACEHOLDER",
        LABEL: "FORM_FIELD.MESSAGE.LABEL",
    },
    SUBMIT: {
        LABEL: "FORM_FIELD.SEND",
    },
    PRIVACY: {
        LABEL: "FORM_FIELD.PRIVACY.LABEL"
    },
    ERRORS: {
        REQUIRED_ERROR_MSG: "FORM_ERRORS.REQUIRED",
        FILE_TYPE_ERROR_MSG: "FORM_ERRORS.FILE_TYPE",
        EMAIL_FORMAT_ERROR_MSG: "FORM_ERRORS.EMAIL_FORMAT",
        PHONE_NUMBER_TOO_LONG: "FORM_ERRORS.PHONE_NUMBER_TOO_LONG",
        PHONE_NUMBER_TOO_SHORT: "FORM_ERRORS.PHONE_NUMBER_TOO_SHORT",
        PHONE_NUMBER_FORMAT_ERROR_MSG: "FORM_ERRORS.PHONE_NUMBER_FORMAT",
        PHONE_PREFIX_FORMAT_ERROR: "FORM_ERRORS.PHONE_PREFIX_FORMAT",
        MESSAGE_TOO_LONG: "FORM_ERRORS.MESSAGE_TOO_LONG",
    }
}