export const LEVEL_LEGENDA_LABELS = {
  HEADER: "LEVEL_LEGEND.TITLE",
  LEVELS: [
    "LEVEL_LEGEND.LEVELS.0",
    "LEVEL_LEGEND.LEVELS.1",
    "LEVEL_LEGEND.LEVELS.2",
    "LEVEL_LEGEND.LEVELS.3",
    "LEVEL_LEGEND.LEVELS.4",
    "LEVEL_LEGEND.LEVELS.5",
    "LEVEL_LEGEND.LEVELS.6",
    "LEVEL_LEGEND.LEVELS.7",
    "LEVEL_LEGEND.LEVELS.8",
    "LEVEL_LEGEND.LEVELS.9",
    "LEVEL_LEGEND.LEVELS.10",
  ],
}